stages:
  - build
  - deploy_k8s

build_images:
  stage: build
  image: docker:20.10.16

  services:
    - docker:20.10.16-dind

  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS

  script:
    - docker build -t manneyvictor/app-dio:1.0 app/.
    - docker push manneyvictor/app-dio:1.0

    - docker build -t manneyvictor/db-dio:1.0 database/.
    - docker push manneyvictor/db-dio:1.0

deploy_k8s:
  stage: deploy_k8s

  script:
    - kubectl --kubeconfig $KUBECONFIG apply -f deployment.yml --record
